removed lvm functions

diff --git a/installimage b/installimage
--- a/installimage
+++ b/installimage
@@ -91,27 +91,27 @@ else
 fi
 
 # Unmount all partitions and print an error message if it fails
-output=$(unmount_all) ; EXITCODE=$?
-if [ $EXITCODE -ne 0 ] ; then
-  echo ""
-  echo -e "${RED}ERROR unmounting device(s):$NOCOL"
-  echo "$output"
-  echo ""
-  echo -e "${RED}Cannot continue, device(s) seem to be in use.$NOCOL"
-  echo "Please unmount used devices manually or reboot the rescuesystem and retry."
-  echo ""
-  exit 1
-fi
-stop_lvm_raid ; EXITCODE=$?
-if [ $EXITCODE -ne 0 ] ; then
-  echo ""
-  echo -e "${RED}ERROR stopping LVM and/or RAID device(s):$NOCOL"
-  echo ""
-  echo -e "${RED}Cannot continue, device(s) seem to be in use.$NOCOL"
-  echo "Please stop used lvm/raid manually or reboot the rescuesystem and retry."
-  echo ""
-  exit 1
-fi
+#output=$(unmount_all) ; EXITCODE=$?
+#if [ $EXITCODE -ne 0 ] ; then
+#  echo ""
+#  echo -e "${RED}ERROR unmounting device(s):$NOCOL"
+#  echo "$output"
+#  echo ""
+#  echo -e "${RED}Cannot continue, device(s) seem to be in use.$NOCOL"
+#  echo "Please unmount used devices manually or reboot the rescuesystem and retry."
+#  echo ""
+#  exit 1
+#fi
+#stop_lvm_raid ; EXITCODE=$?
+#if [ $EXITCODE -ne 0 ] ; then
+#  echo ""
+#  echo -e "${RED}ERROR stopping LVM and/or RAID device(s):$NOCOL"
+#  echo ""
+#  echo -e "${RED}Cannot continue, device(s) seem to be in use.$NOCOL"
+#  echo "Please stop used lvm/raid manually or reboot the rescuesystem and retry."
+#  echo ""
+#  exit 1
+#fi
 
 
 # check if we have a autosetup-file, else we start the menu
